### PR TITLE
Add Firefox download campaign test page

### PR DESCRIPTION
**Pull request by pmac**
Re https://github.com/mozilla/bedrock/issues/8843

### CODE REVIEW

**Comment by pmac** [comment]
I left it loading all static assets from WMO to keep the load on that CDN and the assets cached if people have already visited.

**Comment by bookshelfdave** [comment]
:+1: lgtm!

**Review by bookshelfdave — APPROVED** [review]

**Review by duallain — APPROVED** [review]

**Comment by duallain** [comment]
The original NGINX conf makes this really simple.  It's really nice.

**Comment by pmac** [comment]
To test you can `make run` and then visit http://localhost:8080/en-US/download-firefox/

**Pull request merged**
